fyp/company/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
 path("",views.company.as_view(),name="company"),
 path("/create-interview",views.AddInterview.as_view(),name="create_interview"),
 path("/view/<id>",views.View_CVS.as_view(),name="cvs"),
 path('save_image/', views.save_image, name='save_image'),
 path("save_company_name/",views.save_company_name,name="save_company_name"),
 path("save_bio/",views.save_bio,name="save_bio"),
 path("/reports_view/<id>",views.Reports_view.as_view(),name="reports_view"),
 path("/reports/<id>",views.Reports.as_view(),name="reports")
    
]

fyp/fyp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fyp/company/models.py
from django.db import models
from main.models import CustomUser
from datetime import date

class company(models.Model):
    image = models.ImageField(upload_to='images/', blank=True, null=True,default="images/user1.jpg")
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    desc=models.TextField(max_length=10000,null=True)


    def __str__(self):
        return f"{self.user.name}"
    


class Interview(models.Model):
    company=models.ForeignKey(company,on_delete=models.CASCADE)
    description=models.TextField(max_length=1000,default=" ")
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/')
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    application_end_date = models.DateField()
    schedulded=models.BooleanField(default=False)

    @property
    def is_greater(self):
      return date.today() >= self.start_date
    
    @property
    def is_greater_enddate(self):
      print(date.today(),"asdasd")
      return date.today() >= self.end_date
    



    def __str__(self):
        return f"{self.name}"

class Question(models.Model):
    interview = models.ForeignKey(Interview, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='images/',blank=True, null=True,)
    question_text = models.CharField(max_length=1000)
    answer = models.TextField(max_length=1000)

    def __str__(self):
        mark= "" if self.question_text[-1]=="?" else "?"
        return f"{self.question_text}{mark}"

class User_Answer(models.Model):
    question_inter = models.ForeignKey(Question, on_delete=models.CASCADE)
    user_answer = models.CharField(max_length=1000,default="None")
    semantic_score=models.FloatField(default=0)

    def __str__(self):
        return f"{self.user_answer}"

class Report(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    Spoofing_detection = models.IntegerField(default=0)
    copy_pasting = models.IntegerField(default=0)
    tab_changing = models.IntegerField(default=0)
    user_answers = models.ManyToManyField(User_Answer, related_name='reports')
    interview=models.ForeignKey(Interview,on_delete=models.SET_NULL, null=True)

    def __str__(self):
        user_answers = self.user_answers.all()
        return f" Interview  :{user_answers[0].question_inter.interview.name } User : {self.user.name}"

fyp/company/forms.py
from django.utils import timezone
from django import forms
from .models import Interview, Question


class InterviewForm(forms.ModelForm):
    class Meta:
        model = Interview
        fields = ['name','description','image', 'application_end_date']
    
    widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
            'name':forms.TextInput(attrs={'placeholder':'Enter the name of the Interview'})
        }
    
    def __init__(self, *args, **kwargs):
        super(InterviewForm, self).__init__(*args, **kwargs)

        # Set the input format for date fields
        
        
    def clean(self):
        cleaned_data = super().clean()
        
        application_end_date = cleaned_data.get('application_end_date')
        

        if application_end_date :
            now = timezone.now()
            current_date = now.date()
            
            if application_end_date < current_date:
                self.add_error('application_end_date', 'Application end date must be in the future.')

        return cleaned_data
    

class InterviewDateForm(forms.ModelForm):
    class Meta:
        model = Interview
        fields = ['start_date', 'end_date']

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')

        if start_date and end_date:
            if start_date >= end_date:
                self.add_error('start_date', "Start date must be before end date.")
                self.add_error('end_date', "End date must be after start date.")

            interview = self.instance
            if start_date < interview.application_end_date:
                self.add_error('start_date', "Start date must be before application end date.")

        return cleaned_data
    

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = [ 'question_text', 'answer','image']

QuestionFormSet = forms.modelformset_factory(Question, form=QuestionForm, extra=1)

fyp/company/views.py
from typing import Any
from django.shortcuts import render,redirect
from django.views.generic import TemplateView
from .models import company as Comp, Interview, Question
from .forms import InterviewForm, QuestionFormSet,InterviewDateForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from candidate.models import CVSubmission
from candidate.models import candidate as CANDIDATE
from .models import Interview,company as Company,Report
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime
# Create your views here.

@method_decorator(login_required, name='dispatch')
class company(TemplateView):
    template_name="company.html"

    def get_context_data(self, **kwargs: Any):
        context= super().get_context_data(**kwargs)
        current_user=self.request.user
        compan = Comp.objects.get(user__email=current_user.email)
        context["company"]=compan
        context["image"]=compan.image
        interviews=Interview.objects.filter(company=compan)
        context["interview"]=interviews
        current_date = datetime.now()
       # Format the current date as "Month day, year"
        formatted_date = current_date.strftime("%B %d, %Y")
       # Pass the formatted date to the template context
        context["current_date"] = formatted_date
        return context

    
@method_decorator(login_required, name='dispatch')
class AddInterview(TemplateView):
    template_name="addinterview.html"

    def get_context_data(self, **kwargs):     
        context = super().get_context_data(**kwargs)
        current_user=self.request.user
        compan = Comp.objects.get(user__email=current_user.email)
        context["image"]=compan.image
        context['interview_form'] = InterviewForm()
        context['formset'] = QuestionFormSet(queryset=Question.objects.none())
        return context

    def post(self, request, *args, **kwargs):
        interview_form = InterviewForm(request.POST,request.FILES)
        formset = QuestionFormSet(request.POST, queryset=Question.objects.none())

        if interview_form.is_valid() and formset.is_valid():
          
            current_user=self.request.user
            compan = Comp.objects.get(user__email=current_user.email)

            interview = interview_form.save(commit=False)
            interview.company = compan
            interview.save()

            questions = formset.save(commit=False)
            for question in questions:
                question.interview = interview
                question.save()

            return redirect('/company', pk=interview.pk)
        
        return render(request, self.template_name, {'interview_form': interview_form, 'formset': formset})
    

class View_CVS(TemplateView):
    template_name="csd.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user=self.request.user
        compan = Comp.objects.get(user__email=current_user.email)
        context["image"]=compan.image
        id = kwargs['id']
        interview=Interview.objects.get(id=id)
        context['id'] = id
        context["name"]=interview.name
        context['app_end']=interview.application_end_date
        candidates=CVSubmission.objects.filter(interview__id=id)
        context['candidates']=candidates 
        interview_date_form = InterviewDateForm(instance=interview)
        context['interview_date_form'] = interview_date_form
        return context
    
    def post(self, request, *args, **kwargs):
    
        interview_id = kwargs['id']
        interview=Interview.objects.get(id=interview_id)
        if 'appr' in request.POST:
            candidate_id = request.POST.get("approve")
            candidate = CANDIDATE.objects.get(id=candidate_id)
            CVSubmission.objects.filter(applied_candidate=candidate, interview=interview).update(status='Approved')
            return redirect("cvs", interview_id)

        elif 'rgt' in request.POST:
            print("I am there")
            candidate_id = request.POST.get("reject")
            candidate = CANDIDATE.objects.get(id=candidate_id)
            CVSubmission.objects.filter(applied_candidate=candidate, interview=interview).update(status='Reject')
            return redirect("cvs", interview_id)
          
       
        interview_date_form = InterviewDateForm(request.POST, instance=interview)
        if interview_date_form.is_valid():
            interview_date_form.save()
            interview.schedulded=True
            interview.save()
            return redirect("company")
        else:
            # If form is not valid, re-render the template with form errors
            return render(request, self.template_name, {'interview_date_form': interview_date_form, 'id': interview_id})
            
        return redirect("cvs",interview_id)



@csrf_exempt
def save_image(request):
    if request.method == 'POST' and request.FILES.get('image'):
        image = request.FILES['image']
        cmp_id = request.POST.get('cmp')
        try:
            comp = Company.objects.get(id=cmp_id)
            comp.image = image
            comp.save()
            return JsonResponse({'message': 'Image saved successfully.', 'image_url': comp.image.url})
        except Company.DoesNotExist:
            return JsonResponse({'error': 'Company not found.'}, status=404)
    else:
        return JsonResponse({'error': 'Failed to save image.'}, status=400)



@csrf_exempt
def save_company_name(request):
    if request.method == 'POST':
        company_id = request.POST.get('id')
        new_name = request.POST.get('name')

        try:
            company = Company.objects.get(id=company_id)
            company.user.name = new_name
            company.user.save()
            company.save()
            return JsonResponse({'message': 'Company name saved successfully.'})
        except Company.DoesNotExist:
            return JsonResponse({'error': 'Company not found.'}, status=404)
    else:
        return JsonResponse({'error': 'Invalid request method.'}, status=400)



@csrf_exempt
def save_bio(request):
    if request.method == 'POST':
        bio = request.POST.get('bio')
        company_id = request.POST.get('id')
        try:
            company = Company.objects.get(id=company_id)
            company.desc=bio
            company.save()
            return JsonResponse({'message': 'Company name saved successfully.'})
        except Company.DoesNotExist:
            return JsonResponse({'error': 'Company not found.'}, status=404)  
        
    else:
        return JsonResponse({'error': 'Invalid request method.'}, status=400)


class Reports_view(TemplateView):
    template_name="reports_view.html"

    def get_context_data(self, **kwargs: Any):
        context=super().get_context_data(**kwargs)
        interview_id = kwargs['id']
        interview=Interview.objects.get(id=interview_id)
        context["name"]=interview.name
        data=Report.objects.filter(interview=interview)
        context["reports"]=data
        return context
    

class Reports(TemplateView):
    template_name="report.html"

    def get_context_data(self, **kwargs: Any):
        context=super().get_context_data(**kwargs)
        report_id = kwargs['id']
        data=Report.objects.get(id=report_id)
        sp=data.Spoofing_detection
        tc=data.tab_changing
        fd=data.copy_pasting

        t_score=10-((sp+tc+(fd-1))/3)
        context["t_score"]=t_score

        answers=data.user_answers.all()
        sum=0
        for ans in answers:
            sum=sum+ans.semantic_score
        
        score=10*(sum/len(answers))

        context["p_score"]=score
        

        context["answers"]=answers
        context["report"]=data
        return context

fyp/company/templates/addinterview.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href={% static "css/addinterview.css" %} />
    <title>Create Interview Page</title>
  </head>

  <body>
    <div id="component" class="container-fluid">
      <div class="px-1 row">
        {% include "header.html" with ent=True image=image %}

        <div class="row">
          <div class="col-11 mx-auto align-items-center">
            <h2>Create Interview</h2>
            <form method="post"   id="interview-form"   enctype="multipart/form-data"   >
              {% csrf_token %}

              <div>
                <label for="{{ interview_form.title.id_for_label }}" >Title:</label
                >
                {{ interview_form.name }} 
                {{ interview_form.name.errors }}
                <br />
              </div>

              <div>
                <label for="{{ interview_form.image.image_for_label }}" >Image:</label >
                {{ interview_form.image }} 
                {{ interview_form.image.errors }}
                <br />
              </div>

              <div>
                <label for="{{ interview_form.description.id_for_label }}"
                  >Description:</label
                >
                {{ interview_form.description }} 
                {{ interview_form.name.description }}
                <br />
              </div>

              <div>
                <label
                  for="{{ interview_form.application_end_date.id_for_label }}"
                  >Applications End Date:</label
                >
                <input
                  type="date"
                  name="application_end_date"
                  value=""
                  required=""
                  id="id_application_end_date"
                />
                {% comment %} {{ interview_form.application_end_date }} {%
                endcomment %} {% comment %}
                <input
                  type="text"
                  class="form-control"
                  id="application_end_date"
                  name="interview_end_date"
                  placeholder="YYYY-MM-DD"
                  pattern="\d{4}-\d{2}-\d{2}"
                />
                {% endcomment %} 
                {{ interview_form.application_end_date.errors   }}
                <br />
              </div>

              <hr />
              <div class="w-100 d-flex justify-content-end bg-primary rounded p-1" >
                <button type="button" class="btn btn-primary" onclick="addQuestion()" >
                  Add Question
                </button>
              </div>
              <div id="question-formset">
                {{ formset.management_form }} 
                {% for form in formset %}
                <div class="bg-white border mt-2 mb-2 shadow rounded p-2">
                  <div class="form-row mb-2">
                    <div class="col">
                      <label for="{{ form.question_text.id_for_label }}"  >Question:</label   >
                      {{ form.question_text }} 
                      {{ form.question_text.errors }}
                    </div>
                    <div class="col">
                      <label for="{{ form.answer.id_for_label }}"
                        >Qeustion Image if have</label
                      >
                      {{ form.image }} 
                      {{ form.image.errors }}
                    </div>
                    <div class="col">
                      <label for="{{ form.answer.id_for_label }}"  >Answer:</label >
                      {{ form.answer }} 
                      {{ form.answer.errors }}
                    </div>

                    <div class="col">
                      <div class="d-flex justify-content-start">
                        <button
                          type="button"
                          class="btn btn-danger"
                          onclick="deleteQuestion(this)"
                        >
                          Delete Question
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>

              <div class="d-flex justify-content-center m-4">
                <button type="submit" class="btn btn-primary btn-lg">
                  Apply
                </button>
              </div>
            </form>
          </div>
        </div>

        {% include "footer.html" %} 

    <script>
      function addQuestion() {
        var formset = document.getElementById("question-formset");
        var totalFormsInput = document.getElementById("id_form-TOTAL_FORMS");
        var totalForms = parseInt(totalFormsInput.value);

        // Create a new div for the question form
        var newFormDiv = document.createElement("div");
        newFormDiv.className = "question-form";

        // Add the HTML structure for the question form
        newFormDiv.innerHTML = `
                <div class="bg-white border mt-2 mb-2 shadow rounded p-2  ">
                <label for="id_form-${totalForms}-question_text">Question Text:</label>
                <input type="text" name="form-${totalForms}-question_text" id="id_form-${totalForms}-question_text">

                 <label for="id-form-${totalForms}-image">Qeustion Image if have</label>
                <input type="file" name="form-${totalForms}-image" accept="image/*" id="id_form-${totalForms}-image">
                <label for="id_form-${totalForms}-answer">Answer:</label>
                <textarea type="text" name="form-${totalForms}-answer" id="id_form-${totalForms}-answer" rows="10">
                </textarea>

                
                    <button type="button" class="btn btn-danger " onclick="deleteQuestion(this)">Delete Question</button>
                    
            </div>
            `;

        formset.appendChild(newFormDiv);
        totalFormsInput.value = totalForms + 1;
      }

      function deleteQuestion(button) {
        var formset = document.getElementById("question-formset");
        var totalFormsInput = document.getElementById("id_form-TOTAL_FORMS");
        var totalForms = parseInt(totalFormsInput.value);

        if (totalForms > 1) {
          button.parentElement.remove();
          totalFormsInput.value = totalForms - 1;
        }
      }
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"   crossorigin="anonymous" ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"  integrity="sha384-9Nq0qa2I5kgWGq7M6k7zZukbdJqBOVHpU8JQh1rNOCT8pO2p2eAtKpOzb3aiQ7Ve"   crossorigin="anonymous" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCxFb1CZbKE16xDTtZrsQD72eq4s0D1u7PhshvGL06" crossorigin="anonymous" ></script>
  </body>
</html>

fyp/company/templates/csd.html
<!-- Your HTML file -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Search Interviews</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/cvs.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      {% include "header.html" with ent=True image=image %}
      <div class="container">
        <div class="row">
          <div class="col-11 d-flex justify-content-end schedule_container">
            <p class="">Schedule Interview 🗓️</p>
            {% comment %} <span>{{app_end}}</span> {% endcomment %}
            <form class="text-center" method="POST">
              {% csrf_token %}

              <label for="{{ interview_date_form.start_date.id_for_label }}"
                >From</label
              >
              <input
                type="date"
                name="start_date"
                required="id"
                ="id_start_date"
              />
              {% for error in interview_date_form.start_date.errors %}
              <span class="error">{{ error }}</span>
              {% endfor %}

              <label for="{{ interview_date_form.end_date.id_for_label }}"
                >To</label
              >
              <input type="date" name="end_date" required id="id_end_date" />
              {% comment %} {{ interview_form.end_date }} {% endcomment %} 
              {% comment %}
              <input
                type="text"
                class="form-control"
                id="application_end_date"
                name="interview_end_date"
                placeholder="YYYY-MM-DD"
                pattern="\d{4}-\d{2}-\d{2}"
              />
              {% endcomment %} 
              {% comment %} {{ interview_date_form.end_date.errors }} {% endcomment %} 
              {% for error in interview_date_form.end_date.errors %}
              <span class="error">{{ error }}</span>
              {% endfor %}

              <button type="submit" class="btn btn-dark">Confirm</button>

              {% comment %} <input type="date" /> <input type="date" /> {% endcomment %}
            </form>
          </div>
        </div>
      </div>
      <div class="container-fluid">
        <div class="container">
          <p class="fw-bold text-center mt-4">{{ name }} CVs List</p>
        </div>
      </div>
      <!-- Cvs container -->
      <div class="row d-flex justify-content-around p-3 shadow-lg col-12 col-sm-10 mx-auto cvs_container" >
        <!-- CVs container left -->
        <div class="d-flex flex-column justify-content-start align-items-center shadow-sm py-3 cv_container_left col-12 col-md-7"  >
          <!-- cv card starts-->
          <h3>Appiled Candidates</h3>
    

          {% for candidate in candidates %} 
          {% if candidate.status != "Approved" and candidate.status != "Reject" %}
          <div  class="cv_card col-12 hover-shadow col-sm-11 d-flex justify-content-between p-3 rounded-2 m-2 border border-1" >
            <div>
              <p class="candidate_cv_name m-0 fw-semibold fs-5">
                {{ candidate.applied_candidate.user.name }}
              </p>
              <p class="candiate_profession m-0 fs-6">Full stack developer</p>
              <div class="d-flex">
                <button type="button" class="view_cv_btn text-white p-2 mt-4 me-2 rounded-2 border-0" data-bs-toggle="modal" data-bs-target="#documentModal{{ forloop.counter }}"data-url="{{ candidate.cv.url }}"  >
                View CV
                </button>
                <form method="POST">
                  {% csrf_token %}
                  <button type="submit" class="approve_cv_btn bg-success text-white me-2 p-2 mt-4 rounded-2 border-0" data-toggle="modal" data-target="#exampleModalCenter"  >
                    Approve
                  </button>
                  <input   type="hidden"   value="{{ candidate.applied_candidate.id }}"   name="approve"/>
                  <input type="hidden" value="appr" name="appr" />
                </form>
                <form method="POST">
                  {% csrf_token %}
                  <button type="submit"class="reject_cv_btn bg-danger text-white p-2 mt-4 rounded-2 border-0" data-toggle="modal" data-target="#exampleModalCenter">
                    Reject
                  </button>
                  <input  type="hidden"  value="{{ candidate.applied_candidate.id }}"  name="reject"/>
                  <input type="hidden" value="rgt" name="rgt" />
                </form>
              </div>
            </div>
            <div>
              <a href="#">
                <img src="{{ candidate.applied_candidate.image.url }}" width="120px"alt="candidate pic"class="cv_candidate_pic" />
              </a>
            </div>
          </div>
          {% endif %}
           {% endfor %}
          <!-- cv card ends-->
        </div>
        <!-- Cvs container right -->
        <div class="d-flex flex-column justify-content-start align-items-center shadow-sm cv_right_container p-2 col-12 col-md-4" >
          <!-- cv list item starts-->
          <h3>Selected Candidates</h3>
          {% for app_cand in candidates %} 
          {% if app_cand.status == "Approved"  %}
          <div  class="cv_list_item col-12 col-sm-11 p-3 rounded-2 m-2 border border-1"  >
            <div>
              <p class="interview_name m-0 fw-semibold fs-5">
                {{ app_cand.applied_candidate.user.name }}
              </p>
              <p>{{ app_cand.interview.name }}</p>
              <div class="row">
                <div class="col-12 d-flex justify-content-between cand_pic_cont" >
                  {% comment %}
                  <button
                    class="delete_interview_cvs_btn bg-danger text-white p-2 mt-4 rounded-2 border-0"
                  >
                    Remove
                  </button>
                  {% endcomment %}

                  <a href="#">
                    <img  src={{ app_cand.applied_candidate.image.url }}  alt="candidate pic" />
                  </a>
                </div>
              </div>
            </div>
          </div>
          {% endif %} 
          {% endfor %}
          <!-- cv list item ends-->
        </div>
      </div>
    </div>
    {% include "footer.html" %}
    <!-- Bootstrap JavaScript and dependencies -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script   src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"   integrity="sha384-BBmZ1C91SbRE4Sx6WBDerP3b0jSqbzjNefoXr1N0Ib4P/sCr+qESV3PR4RlnXN8h"   crossorigin="anonymous"></script>
    <script    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"   integrity="<computed SHA-384 integrity>"   crossorigin="anonymous"></script>

    <!-- Modal for each candidate -->
    {% for candidate in candidates %}
    <div  class="modal fade"   id="documentModal{{ forloop.counter }}"   tabindex="-1"   aria-labelledby="documentModalLabel" aria-hidden="true" >
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="documentModalLabel">CV Viewer</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <object type="application/pdf" data="{{ candidate.cv.url }}" style="width: 100%; height: 500px">
               <p>
                It appears you don't have a PDF plugin for this browser. You can
                <a href="{{ candidate.cv.url }}">click here to download the PDF file.</a>
              </p> 
            </object type>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}

    <script>
      document.addEventListener("DOMContentLoaded", function () {
        var modalTriggerButtons = document.querySelectorAll( '[data-bs-toggle="modal"]');
        modalTriggerButtons.forEach(function (button) {
          button.addEventListener("click", function () {
            var documentUrl = button.getAttribute("data-url");
            var modal = document.querySelector(
              button.getAttribute("data-bs-target")
            );
            var objectTag = modal.querySelector("object");
            objectTag.data = documentUrl;
          });
        });
      });
    </script>
  </body>
</html>